메모화면 구성
f-lab-edu/MemoZip pull request #25
Opened 2024-05-07 11:47 UTC by hiereit-dev

2024-05-07 13:26 UTC, f-lab-frank requested changes

2024-05-07 13:26 UTC, f-lab-frank commented on MyLibrary/View/HomeViewController/HomeViewController.swift
> +                let viewController = self.routing.addMemoViewController() as! AddMemoViewController
이 부분을 `AddMemoViewController`로 캐스팅하게 되면 다시 `HomeViewController`가 `AddMemoViewController`에 의존하게 됩니다. `routing.addMemoViewController()`의 parameter로 handler를 전달하면 어떨까요? `AddMemoViewController`의 입장에서는 생성자를 통해서 전달받아야 합니다.

2024-05-07 13:26 UTC, f-lab-frank commented on MyLibrary/View/AddMemoViewController/AddMemoViewController.swift
> +        self.addMemoHandler?(["result": true, "memo": memo])
아직 `Memo` type을 정의하지 않았기 때문에 이 부분을 `[String: Any]` type으로 처리한 것인가요?

2024-05-07 13:26 UTC, f-lab-frank commented on MyLibrary/View/AddMemoViewController/AddMemoViewController.swift
> +        self.addMemoHandler?(["result": false, "memo": ""])
Cancel의 경우, 호출한 쪽(`HomeViewController`)에서 따로 더 해줄 게 있는지 여부를 판단할 필요가 있습니다. 만약 아무 동작도 안 할 거라면 아예 무시해도 괜찮을 것 같습니다.

혹은 Cancel 시, 별도의 시나리오가 있는 상황이라고 하면 closure를 별도로 정의하는 것이 좋습니다. Delegate을 정의하는 것도 하나의 방법입니다.

2024-05-08 00:47 UTC, hiereit-dev commented on MyLibrary/View/AddMemoViewController/AddMemoViewController.swift
> +        self.addMemoHandler?(["result": false, "memo": ""])
`addMemoHandler`의 역할은 textVie에 담긴 memo를 homeViewController쪽으로 전달하는 역할뿐이기 때문에,  `addMemoHandler` [String: Any] -> () 를  `messageHandler` -> (String)-> () 으로 수정하는 방향으로 하겠습니다!

2024-05-08 00:48 UTC, hiereit-dev commented on MyLibrary/View/HomeViewController/HomeViewController.swift
> +                let viewController = self.routing.addMemoViewController() as! AddMemoViewController
`routing.addMemoViewController()`의 parameter로 handler를 전달하는 방법으로 수정하겠습니다!

2024-05-08 00:48 UTC, hiereit-dev commented on MyLibrary/View/AddMemoViewController/AddMemoViewController.swift
> +        self.addMemoHandler?(["result": true, "memo": memo])
단순히 작성한 memo만 전달하면 될거라 생각해서 Memo Type을 사용하지 않았습니다.

2024-05-08 01:51 UTC, merged