SET: fmdb 설정 & write/read 완료
f-lab-edu/MemoZip pull request #28
Opened 2024-05-10 12:09 UTC by hiereit-dev

- fmdb 설정
  - package.swift `FMDB`추가
- read / write 구현
  - memoRepository` fetch()` 구현
  - memoRepository `create(content: String)` 구현
- `Memo` 모델 생성

2024-05-12 13:40 UTC, f-lab-frank requested changes

2024-05-12 13:40 UTC, f-lab-frank commented on MyLibrary/Repository/Implementation/MemoRepositoryImp.swift
> +    public lazy var fmdb: FMDatabase! = {
`db.sqlite` 파일명을 `RepositoryImp` module 내부에 하드코딩하기엔 너무 일반적인 이름입니다. `MemoRepository` 외에 다른 repository가 마찬가지로 db를 사용하게 된다고 생각해볼 때, 그 repository의 `fmdb` property는 어떻게 구현하게 될지 상상해보면 좋을 것 같습니다.

2024-05-12 13:40 UTC, f-lab-frank commented on MyLibrary/View/HomeViewController/HomeViewController.swift
> +import RepositoryImp
HomeViewController가 RepositoryImp에 직접 의존해서는 안됩니다. ViewModel을 통해서 호출해야만 합니다.

2024-05-12 13:40 UTC, f-lab-frank commented on MyLibrary/View/HomeViewController/HomeViewController.swift
> +                    if MemoRepositoryImp().create(content: memo) {
`AddMemoViewController`에 로직을 두지 않고 `HomeViewController`가 callback을 통해 처리하는 것은 선택 사항입니다. 하지만 `MemoRepositoryImp`를 직접 생성하고 호출하는 것은 안됩니다. `TodoRepository`나 `PlanRepository`를 누가 들고 있으면서 호출하고 있는지 살펴보면 좋을 것 같습니다.

2024-05-17 23:52 UTC, f-lab-frank commented on MyLibrary/ViewModel/Model/MemoViewModel.swift
> +public class MemoViewModel: MemoRepository {
지금 구성을 어떻게 할 계획이신지 약간 헷갈립니다.

1. 현재 MemoZip은 Reactor를 이용해서 ViewModel을 구현하고 있었는데, `MemoViewModel`은 다른 스타일로 구현하려고 생각하는 게 맞나요? 설사 그렇다고 하더라도 `MemoViewModel`이 `MemoRepository`를 conform하는 것은 좀 이상한 것 같습니다. dbManager를 `MemoRepositoryImp`가 직접 들고 있게 해두고, ViewModel이 Repository를 property로 가져야 합니다.

2. ViewModel은 View와 매칭되는 개념으로 생각해야하는데, MemoViewModel이 어떤 View와 매칭되는 상황인가요?

2024-05-20 02:23 UTC, hiereit-dev commented on MyLibrary/ViewModel/Model/MemoViewModel.swift
> +public class MemoViewModel: MemoRepository {
ViewModel을 사용해야겠다. 생각이 들어서 수정하다보니 이상하게 구현하게 됐습니다. 리뷰를 보고, `appComponent`에서 주입받는 방법을 사용하는 방향으로 다시 수정했습니다.

2024-05-20 12:55 UTC, f-lab-frank approved these changes
LGTM

2024-05-20 12:55 UTC, f-lab-frank commented on MyLibrary/View/HomeViewController/HomeViewController.swift
> +    private let memoRepository: MemoRepository
`HomeViewReactor`가 이미 `MemoRepository`를 들고 있는 있습니다. View는 오직 ViewModel에만 의존해야지 Repository에 의존해서는 안됩니다. `MemoRepository`를 직접 사용하지말고 `HomeViewReactor`를 통해서 호출하는 것이 좋겠습니다.

일단 이번 PR이 길어지고 있고, 뒤에 연결된 PR도 있으니 approve 하도록 하겠습니다. 별도 PR로 마저 수정해주세요.

2024-05-20 13:44 UTC, merged